version: '2'
services:
  mongo:
    build: ./mongo/
    ports:
      - "27017:27017"

  backend:
    build: ./backend/
    ports:
      - "5000:5000"
      - "4333:4333"
    volumes:
      - ./backend/:/var/www/
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
